name: Build Astra Browser

on:
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller AstraBrowser.spec

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: AstraBrowser-Windows
          path: dist/AstraBrowser/**

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Qt dependencies
        run: |
          sudo apt update
          sudo apt install -y libgl1 libegl1 libxkbcommon0 zip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux
        run: |
          pyinstaller AstraBrowser.spec

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: AstraBrowser-Linux
          path: dist/AstraBrowser/**

  release:
    needs:
      - windows
      - linux

    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip Windows Build
        run: |
          cd artifacts/AstraBrowser-Windows
          zip -r ../../AstraBrowser-Windows.zip .

      - name: Zip Linux Build
        run: |
          cd artifacts/AstraBrowser-Linux
          zip -r ../../AstraBrowser-Linux.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AstraBrowser-Windows.zip
            AstraBrowser-Linux.zip