name: Build Astra Browser

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt
      - run: pip install pyinstaller

      - run: pyinstaller --windowed --name AstraBrowser main.py

      - uses: actions/upload-artifact@v4
        with:
          name: AstraBrowser-Windows
          path: dist/**

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: sudo apt update

      - run: |
          sudo apt install -y \
          libegl1 \
          libgl1 \
          libxkbcommon-x11-0 \
          dpkg-dev \
          fakeroot \
          ruby-full

      - run: pip install -r requirements.txt
      - run: pip install pyinstaller

      - run: pyinstaller --windowed --name AstraBrowser main.py

      - name: Install fpm
        run: sudo gem install --no-document fpm

      - name: Create DEB
        run: |
          mkdir package
          cp -r dist/AstraBrowser package/

          fpm \
            -s dir \
            -t deb \
            -n astrabrowser \
            -v 0.1.0 \
            package/=/

      - name: Download linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Build AppImage
        run: |
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --executable dist/AstraBrowser/AstraBrowser \
            --output appimage

      - uses: actions/upload-artifact@v4
        with:
          name: AstraBrowser-Linux
          path: |
            *.deb
            *.AppImage
            dist/**